# Generated by Django 4.1.5 on 2023-01-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoteBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "notebook",
                "verbose_name_plural": "notebooks",
                "db_table": "notebook",
            },
        ),
    ]
