# Generated by Django 4.1.5 on 2023-01-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebooks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notebook",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="title",
            field=models.CharField(blank=True, default="no title", max_length=100),
        ),
    ]
